### ISSUE TITLE
Rbexy Fails to Load

### ISSUE THREAD

**Issue by zacheryph** [patbenatar/rbexy#100]
Whenever trying to add Rbexy to a project you can no longer actually start up the server or console. The following error shows. This is `2.0.0.rc4`. I tried on the following pairings to the same result. Zeitwerk is.... lovely.
* Ruby 3.1.4, Rails 7.0.8
* Ruby 3.1.4, Rails 7.1.3.2
* Ruby 3.2.3, Rails 7.1.3.2
* Ruby 3.3.0, Rails 7.1.3.2

The only way around this that I can see is to `require: false` in the `Gemfile` and `require "rbexy"; require "rbexy/rails/engine"` _after_ Bundler loads everything.

### Error
```
/Users/context/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/actionview-7.1.3.2/lib/action_view/helpers/tag_helper.rb:17:in
`<module:TagHelper>': uninitialized constant ActionView::Helpers::TagHelper::OutputSafetyHelper (NameError)

      include OutputSafetyHelper
              ^^^^^^^^^^^^^^^^^^
```

**Comment by patbenatar** [comment]
We may just need to explicitly require that file from action_view at the top of our file that uses it, like what we do [here](https://github.com/patbenatar/rbexy/blob/master/lib/rbexy/rails/component_template_resolver.rb#L1)

**Comment by zacheryph** [comment]
@patbenatar Yeah... I spent a good 30 minutes trying a number of different ways of not just doing `require 'action_view'` but I just continued to get this or other similar errors. In the end the hassle wasn't worth it.
